added quality gate - check api coverage

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -59,6 +59,17 @@ jobs: #  аналог этапов
         if: always()
         run: sudo cp swagger-coverage-report.html allure-history/${{ github.run_number }}
 
+      - name: Quality Gate (Check API Coverage)
+        if: always()
+        run: |
+          REPORT="allure-history/${{ github.run_number }}/widgets/coverage.json"
+          COVERAGE=$(jq '.percentage' "$REPORT")
+          
+          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
+          echo "Quality gate failed: API coverage is less than 50%"
+          exit 1
+          fi
+
       - name: Publish test report
         uses: peaceiris/actions-gh-pages@v3
         if: always()
